name: Update outdated dependencies

on:
    schedule:
        - cron: '0 20 * * 1-4'
    workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install pip-tools
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip pip-tools

      - name: Upgrade outdated dependencies
        run: |
          items=($(
              jq -r '.[1:]' "scripts/make_release_requirements.json" |
              jq -r '.[] | "\(.name)|\(.version)"'
          ))
          for item in "${items[@]}"; do
              IFS='|' read -r "package_name" "package_version" <<< "${item}"
              echo "found outdated package:"
              echo "name: ${package_name}"
              echo "version: ${package_version}"
              # TODO: Attempt to upgrade the package.
          done

          echo "done"